name: "Swift Build and Test"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Select Xcode 12
      run: sudo xcode-select -switch /Applications/Xcode_13.4.1.app
      
    - name: Build and Test
      run: xcodebuild clean build test -workspace Github-Action-WorkFlow-Sample.xcworkspace -scheme "Github-Action-WorkFlow-Sample" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=YES

